[package]
name = "fourkay"
version = "0.1.0"
authors = ["Aleksander Vognild Burkow <aleksanderburkow@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = {version = "0.2.*", default-features = false}

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
