[package]
name = "bindings"
version = "0.1.0"
authors = ["Aleksander Vognild Burkow <aleksanderburkow@gmail.com>"]
edition = "2018"

[dependencies]
libc = {version = "0.2.*", default-features = false}

[build-dependencies]
bindgen = "0.42.*"
